# Generated by Django 6.0.5 on 2026-06-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('category', models.CharField(choices=[('EQUIPMENT', 'Équipement'), ('FURNITURE', 'Mobilier'), ('IT', 'Informatique'), ('STATIONERY', 'Fournitures de bureau'), ('OTHER', 'Autre')], default='OTHER', max_length=12, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité')),
                ('min_quantity', models.IntegerField(default=0, verbose_name="Seuil d'alerte")),
                ('unit', models.CharField(default='unité', max_length=30, verbose_name='Unité')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation (rayon/étagère)')),
                ('status', models.CharField(choices=[('GOOD', 'En bon état'), ('REPAIR', 'En réparation'), ('OUT_OF_SERVICE', 'Hors service')], default='GOOD', max_length=14, verbose_name='État')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix unitaire (FCFA)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stock/items/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='Objet / Motif')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée'), ('RETURNED', 'Retourné')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décidé le')),
                ('return_note', models.TextField(blank=True, verbose_name='Note de retour')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='stock.stockitem', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Demande d'emprunt",
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement')], max_length=10, verbose_name='Type')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motif')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Effectué le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem', verbose_name='Article')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.stocksupplier', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('items', models.TextField(verbose_name='Articles commandés')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant total (FCFA)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('RECEIVED', 'Reçue'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Date de réception')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stock.stocksupplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'ordering': ['-order_date'],
            },
        ),
    ]
