# Generated by Django 6.0.5 on 2026-06-12 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='brand_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marque / Modèle'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Valeur estimée (FCFA)'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='mat_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Matériel'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Série'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='departure_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='État départ'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destination / Utilisateur'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='mvt_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='origin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Provenance'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='return_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='État retour'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='store_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_movements', to=settings.AUTH_USER_MODEL, verbose_name='Responsable magasin'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('EVENEMENT', 'Événement'), ('TECHNIQUE', 'Technique / Son-Lumière'), ('IT', 'Informatique'), ('MOBILIER', 'Mobilier'), ('CONSOMMABLE', 'Consommable'), ('BUREAUTIQUE', 'Fournitures bureau'), ('EQUIPMENT', 'Équipement général'), ('OTHER', 'Autre')], default='OTHER', max_length=12, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localisation (rayonnage/zone)'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité totale'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence interne'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'Neuf'), ('GOOD', 'Bon état'), ('USED', 'Usé'), ('REPAIR', 'En réparation'), ('OUT_OF_SERVICE', 'Hors service (HS)')], default='GOOD', max_length=15, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement'), ('TRANSFER', 'Transfert'), ('BORROW', 'Emprunt'), ('RETURN', 'Retour')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='stocksupplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact'),
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(verbose_name='Problème constaté')),
                ('detected_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date de détection')),
                ('recommended_action', models.CharField(choices=[('DIAGNOSE', 'Diagnostiquer'), ('REPAIR', 'Réparer'), ('SCRAP', 'Jeter / Rebut'), ('WAIT', 'Attendre'), ('REPLACE', 'Remplacer')], default='DIAGNOSE', max_length=10, verbose_name='Action recommandée')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Coût estimé (FCFA)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('SCRAPPED', 'Mis au rebut')], default='PENDING', max_length=12, verbose_name='Statut')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='stock.stockitem', verbose_name='Matériel')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_items', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Fiche de maintenance',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='PostEventReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Événement')),
                ('event_date', models.DateField(verbose_name="Date de l'événement")),
                ('qty_out', models.IntegerField(verbose_name='Qté sortie')),
                ('qty_returned', models.IntegerField(default=0, verbose_name='Qté revenue')),
                ('return_state', models.CharField(choices=[('GOOD', 'Bon'), ('USED', 'Usé'), ('DAMAGED', 'Endommagé'), ('MISSING', 'Manquant')], default='GOOD', max_length=10, verbose_name='État retour')),
                ('action', models.CharField(choices=[('OK', 'RAS'), ('REPAIR', 'Réparer'), ('REPLACE', 'Remplacer'), ('INVESTIGATE', 'Enquêter')], default='OK', max_length=12, verbose_name='Action')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='stock.stockitem', verbose_name='Matériel')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Réconciliation post-événement',
                'ordering': ['-event_date'],
            },
        ),
    ]
