# Generated by Django 6.0.5 on 2026-06-03 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Code')),
                ('kind', models.CharField(choices=[('CAMPAIGN', 'Campagne marketing'), ('EVENT', 'Événement'), ('OTHER', 'Autre projet')], default='CAMPAIGN', max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description / Brief')),
                ('status', models.CharField(choices=[('PLANNED', 'À démarrer'), ('ACTIVE', 'En cours'), ('ON_HOLD', 'En pause'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=10, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Budget alloué (FCFA)')),
                ('spent', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Budget consommé (FCFA)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('providers', models.TextField(blank=True, verbose_name='Prestataires')),
                ('attendees_expected', models.PositiveIntegerField(blank=True, null=True, verbose_name='Participants attendus')),
                ('attendees_actual', models.PositiveIntegerField(blank=True, null=True, verbose_name='Participants réels')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='business.client', verbose_name='Client')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet')),
                ('team', models.ManyToManyField(blank=True, related_name='projets_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Équipe projet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets & événements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Phase')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('DOING', 'En cours'), ('DONE', 'Terminée')], default='TODO', max_length=6, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'verbose_name': 'Phase',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/%Y/%m/', verbose_name='Fichier')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média de projet',
                'verbose_name_plural': 'Médias de projet',
                'ordering': ['-created_at'],
            },
        ),
    ]
