# Generated by Django 6.0.5 on 2026-06-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_emergency_contact2_and_more'),
        ('projects', '0003_benchmark_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='employees.department', verbose_name='Département'),
        ),
    ]
