# Generated by Django 6.0.5 on 2026-06-02 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom du département')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_departements', to='employees.department', verbose_name='Rattaché à')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Intitulé du poste')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['title'],
                'unique_together': {('title', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'embauche")),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI — Contrat à durée indéterminée'), ('CDD', 'CDD — Contrat à durée déterminée'), ('STAGE', 'Stage'), ('TEMP', 'Temporaire / Mission')], default='CDI', max_length=10, verbose_name='Type de contrat')),
                ('status', models.CharField(choices=[('ACTIVE', 'En activité'), ('LEAVE', 'En congé'), ('SUSPENDED', 'Suspendu'), ('TERMINATED', 'Sorti des effectifs')], default='ACTIVE', max_length=12, verbose_name='Statut')),
                ('cnps_number', models.CharField(blank=True, help_text='Caisse Nationale de Prévoyance Sociale', max_length=30, verbose_name='N° CNPS')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, default='Douala', max_length=80, verbose_name='Ville')),
                ('emergency_contact', models.CharField(blank=True, max_length=150, verbose_name="Contact d'urgence")),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Département')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='employees.employee', verbose_name='Responsable hiérarchique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
