# Generated by Django 6.0.5 — passage département/poste uniques → multiples.

from django.db import migrations, models


def copy_to_m2m(apps, schema_editor):
    """Copie le département et le poste uniques existants vers les relations multiples."""
    Employee = apps.get_model("employees", "Employee")
    for emp in Employee.objects.all():
        if emp.department_id:
            emp.departments.add(emp.department_id)
        if emp.position_id:
            emp.positions.add(emp.position_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_position_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='employees', to='employees.department', verbose_name='Départements'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='holders', to='employees.position', verbose_name='Postes / fonctions'),
        ),
        migrations.RunPython(copy_to_m2m, noop),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
