# Generated by Django 6.0.5 on 2026-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_multi_dept_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Matricule'),
        ),
    ]
