# Generated by Django 6.0.5 on 2026-06-05 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contact2',
            field=models.CharField(blank=True, max_length=150, verbose_name='2e contact — Nom (optionnel)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact2_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?\\d[\\d\\s.\\-]{7,18}$', 'Numéro de téléphone invalide (8 à 15 chiffres, ex. +237 6 99 00 00 00).')], verbose_name='2e contact — Téléphone (optionnel)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?\\d[\\d\\s.\\-]{7,18}$', 'Numéro de téléphone invalide (8 à 15 chiffres, ex. +237 6 99 00 00 00).')], verbose_name='Personne à contacter — Téléphone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=150, verbose_name='Personne à contacter — Nom'),
        ),
    ]
