# Generated by Django 6.0.5 on 2026-06-19 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_emergency_contact2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='departements_codiriges', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Responsable principal'),
        ),
    ]
