# Generated by Django 6.0.5 on 2026-06-02 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('reference', models.CharField(blank=True, max_length=40, verbose_name='Référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'À démarrer'), ('ACTIVE', 'En cours'), ('ON_HOLD', 'En pause'), ('DONE', 'Terminé')], default='ACTIVE', max_length=10, verbose_name='Statut')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Avancement (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(help_text="Utilisateur externe propriétaire de l'espace.", on_delete=django.db.models.deletion.CASCADE, related_name='projets_client', to=settings.AUTH_USER_MODEL, verbose_name='Client / partenaire')),
                ('internal_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_pilotes', to=settings.AUTH_USER_MODEL, verbose_name='Chargé de compte (LPM)')),
            ],
            options={
                'verbose_name': 'Projet (extranet)',
                'verbose_name_plural': 'Projets (extranet)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtranetMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='extranet.project')),
            ],
            options={
                'verbose_name': 'Message extranet',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='extranet/%Y/%m/', verbose_name='Fichier')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('direction', models.CharField(choices=[('TO_CLIENT', 'LPM → Client'), ('FROM_CLIENT', 'Client → LPM')], max_length=12, verbose_name='Sens')),
                ('validation', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10, verbose_name='Validation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='extranet.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extranet_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier de projet',
                'verbose_name_plural': 'Fichiers de projet',
                'ordering': ['-created_at'],
            },
        ),
    ]
