# Generated by Django 6.0.5 on 2026-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('REPORT', 'Rapport')], default='DOCUMENT', max_length=10, verbose_name='Type'),
        ),
    ]
