# Generated by Django 6.0.5 on 2026-06-03 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0002_projectfile_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CAMPAIGN', 'Nouvelle campagne'), ('QUOTE', 'Demande de devis'), ('GRAPHIC', 'Création graphique'), ('EVENT', 'Événement')], default='CAMPAIGN', max_length=10, verbose_name='Type de demande')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('details', models.TextField(verbose_name='Détails / besoin')),
                ('budget', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Budget indicatif (FCFA)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Échéance souhaitée')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumise'), ('IN_REVIEW', 'En étude'), ('ACCEPTED', 'Acceptée'), ('DECLINED', 'Refusée')], default='SUBMITTED', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Demande client',
                'verbose_name_plural': 'Demandes clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, verbose_name='Référence')),
                ('kind', models.CharField(choices=[('INCIDENT', 'Incident'), ('RECLAMATION', 'Réclamation'), ('ASSISTANCE', "Demande d'assistance")], default='RECLAMATION', max_length=12, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=12, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Pris en charge par')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='extranet.project', verbose_name='Projet concerné')),
            ],
            options={
                'verbose_name': 'Réclamation / ticket',
                'verbose_name_plural': 'Réclamations / tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='extranet.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
