# Generated by Django 6.0.5 on 2026-06-03 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranet', '0003_clientrequest_ticket_ticketreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('status', models.CharField(choices=[('IN_REVIEW', 'En revue'), ('CHANGES', 'Corrections demandées'), ('APPROVED', 'Validée')], default='IN_REVIEW', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creatives_crees', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='extranet.project')),
            ],
            options={
                'verbose_name': 'Création graphique',
                'verbose_name_plural': 'Créations graphiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('file', models.FileField(upload_to='creatives/%Y/%m/', verbose_name='Visuel')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note du graphiste')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CHANGES', 'Corrections demandées'), ('APPROVED', 'Validée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='extranet.creative')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('creative', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CreativeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='extranet.creativeversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
