# Generated by Django 6.0.5 on 2026-06-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSEIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CARBON', 'Empreinte carbone'), ('DIVERSITY', 'Diversité & inclusion'), ('SOCIAL', 'Impact social'), ('GOVERNANCE', 'Gouvernance')], max_length=12, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'indicateur")),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur')),
                ('unit', models.CharField(max_length=50, verbose_name='Unité')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Objectif')),
                ('year', models.IntegerField(default=2026, verbose_name='Année')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Indicateur RSE',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RSEResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('kind', models.CharField(choices=[('GUIDE', 'Guide'), ('ELEARNING', 'E-learning'), ('QUIZ', 'Quiz'), ('ECO_TIP', 'Éco-geste')], max_length=10, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='rse/resources/', verbose_name='Fichier')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Ressource RSE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSESupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('criteria', models.TextField(verbose_name='Critères RSE évalués')),
                ('score', models.IntegerField(default=5, verbose_name='Score (0-10)')),
                ('certified', models.BooleanField(default=False, verbose_name='Certifié')),
                ('policy_url', models.URLField(blank=True, verbose_name='URL politique RSE')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('evaluated_at', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
            ],
            options={
                'verbose_name': 'Fournisseur RSE',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='RSEInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('SOLIDARITY', 'Solidarité'), ('PARTNERSHIP', 'Partenariat'), ('VOLUNTEERING', 'Bénévolat'), ('ECO', 'Écologie'), ('OTHER', 'Autre')], default='OTHER', max_length=12, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('ACTIVE', 'En cours'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=10, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('impact', models.TextField(blank=True, verbose_name='Impact attendu / réalisé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rse_initiatives', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Initiative RSE',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Année')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('document', models.FileField(blank=True, null=True, upload_to='rse/reports/', verbose_name='Document PDF')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rse_reports', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Rapport RSE',
                'ordering': ['-year'],
            },
        ),
    ]
