# Generated by Django 6.0.5 on 2026-06-03 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom du candidat')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('cv', models.FileField(blank=True, null=True, upload_to='hr/cv/%Y/', verbose_name='CV')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle candidature'), ('SHORTLIST', 'Présélectionné'), ('INTERVIEW', 'En entretien'), ('HIRED', 'Recruté'), ('REJECTED', 'Non retenu')], default='NEW', max_length=10, verbose_name='Statut')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Note (/5)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('TEMP', 'Temporaire / Mission')], default='CDI', max_length=10, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Intitulé du poste')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Salaire mensuel brut (FCFA)')),
                ('file', models.FileField(blank=True, null=True, upload_to='hr/contracts/%Y/', verbose_name='Contrat signé (PDF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='ex. Année 2026 — S1', max_length=40, verbose_name='Période')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('VALIDATED', 'Validée')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('comment', models.TextField(blank=True, verbose_name='Appréciation générale')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='employees.employee')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_menees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Date & heure')),
                ('mode', models.CharField(default='Présentiel', max_length=12, verbose_name='Mode')),
                ('feedback', models.TextField(blank=True, verbose_name='Compte-rendu')),
                ('recommendation', models.CharField(blank=True, choices=[('FAVORABLE', 'Favorable'), ('RESERVE', 'Avec réserve'), ('DEFAVORABLE', 'Défavorable')], max_length=12, verbose_name='Recommandation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hr.candidate')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entretien',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Poste à pourvoir')),
                ('description', models.TextField(blank=True, verbose_name='Description du poste')),
                ('positions', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de postes')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('CLOSED', 'Clôturé')], default='OPEN', max_length=8, verbose_name='Statut')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openings', to='employees.department')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='hr.jobopening'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Objectif')),
                ('kpi', models.CharField(blank=True, max_length=200, verbose_name='Indicateur (KPI)')),
                ('weight', models.PositiveSmallIntegerField(default=20, verbose_name='Poids (%)')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Atteinte (%)')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='hr.evaluation')),
            ],
            options={
                'verbose_name': 'Objectif / KPI',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Arrivée')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Départ')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('LATE', 'En retard'), ('ABSENT', 'Absent'), ('LEAVE', 'En congé')], default='PRESENT', max_length=8, verbose_name='Statut')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
