# Generated by Django 6.0.5 on 2026-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude arrivée'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude arrivée'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance au bureau (m)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_site',
            field=models.BooleanField(default=False, verbose_name='Pointé sur site'),
        ),
    ]
