# Generated by Django 6.0.5 on 2026-06-05 16:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_multi_dept_position'),
        ('hr', '0003_officelocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Présent'), ('LATE', 'En retard'), ('ABSENT', 'Absent'), ('LEAVE', 'En congé'), ('MISSION', 'En mission')], default='PRESENT', max_length=8, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Du')),
                ('end_date', models.DateField(verbose_name='Au')),
                ('destination', models.CharField(blank=True, max_length=150, verbose_name='Destination / lieu')),
                ('objet', models.TextField(blank=True, verbose_name='Objet de la mission')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistrée par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='employees.employee', verbose_name='Personne en mission')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_coefficient', models.DecimalField(decimal_places=2, default=1, help_text='Multiplie la retenue prorata des retards (1,00 = 100 %, 0,50 = moitié, 0 = aucune).', max_digits=5, verbose_name='Coefficient de retenue sur retard')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre de paie',
                'verbose_name_plural': 'Paramètres de paie',
            },
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mois (1er jour)')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant retenu (FCFA)')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_adjustments', to='employees.employee')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_paie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajustement de retenue',
                'verbose_name_plural': 'Ajustements de retenue',
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
