# Generated by Django 6.0.5 on 2026-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_attendance_status_mission_payrollsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='birth_info',
            field=models.CharField(blank=True, max_length=150, verbose_name='Date et lieu de naissance'),
        ),
        migrations.AddField(
            model_name='contract',
            name='duties',
            field=models.TextField(blank=True, verbose_name='Fonctions et responsabilités (une par ligne)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prime de logement (FCFA)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='N° CNI / Passeport'),
        ),
        migrations.AddField(
            model_name='contract',
            name='nationality',
            field=models.CharField(blank=True, default='Camerounaise', max_length=60, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='contract',
            name='other_allowances',
            field=models.CharField(blank=True, max_length=200, verbose_name='Autres primes / avantages'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pay_day',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Jour de paiement du salaire'),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prime de rendement (FCFA)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='place_signed',
            field=models.CharField(blank=True, default='Douala', max_length=80, verbose_name='Fait à'),
        ),
        migrations.AddField(
            model_name='contract',
            name='probation_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Période d'essai (mois)"),
        ),
        migrations.AddField(
            model_name='contract',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prime de transport (FCFA)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu de travail'),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_schedule',
            field=models.CharField(blank=True, default='Du lundi au vendredi, de 08h00 à 17h00', max_length=200, verbose_name='Horaires de travail'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Salaire mensuel de base (FCFA)'),
        ),
    ]
