# Generated by Django 6.0.5 on 2026-06-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_is_confidential'),
        ('employees', '0005_employee_emergency_contact2_and_more'),
        ('hr', '0005_contract_birth_info_contract_duties_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du parcours')),
                ('description', models.TextField(blank=True)),
                ('role_target', models.CharField(blank=True, max_length=50, verbose_name='Rôle visé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Plan d'intégration",
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True)),
                ('day', models.PositiveSmallIntegerField(default=1, verbose_name='Jour J+')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_steps', to='documents.document')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hr.onboardingplan')),
            ],
            options={
                'verbose_name': "Étape d'intégration",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='Démarré le')),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='employees.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='hr.onboardingplan')),
                ('completed_steps', models.ManyToManyField(blank=True, related_name='completed_by', to='hr.onboardingstep')),
            ],
            options={
                'verbose_name': "Suivi d'intégration",
                'unique_together': {('employee', 'plan')},
            },
        ),
    ]
