# Generated by Django 6.0.5 on 2026-06-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_onboardingplan_onboardingstep_onboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début du pointage'),
        ),
    ]
