# Generated by Django 6.0.5 on 2026-06-19 07:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_officelocation_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollsetting',
            options={'verbose_name': 'Paramètre de pointage & paie', 'verbose_name_plural': 'Paramètres de pointage & paie'},
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='checkout_enabled_min',
            field=models.PositiveSmallIntegerField(default=900, help_text='Le bouton « Pointer le départ » reste grisé avant cette heure (15h00).', verbose_name='Activation du pointage de départ'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='late_recovery_max_min',
            field=models.PositiveSmallIntegerField(default=30, help_text="Un retard supérieur à cette durée n'est jamais rattrapable par heures sup (30 min).", verbose_name='Retard maximum rattrapable'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='late_threshold_min',
            field=models.PositiveSmallIntegerField(default=490, help_text='Une arrivée APRÈS cette heure est comptée « En retard » (08h10 = 08h00 + 10 min de tolérance).', verbose_name="Heure limite d'arrivée"),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='monthly_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('173.33'), help_text='Durée légale mensuelle (40 h/sem → 173,33 h). Base du taux horaire.', max_digits=6, verbose_name='Heures légales mensuelles'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='ot_rate_night',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Travail de nuit (22h–06h) : +50 %.', max_digits=5, verbose_name='Majoration heures de nuit (%)'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='ot_rate_sunday',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Heures effectuées un dimanche ou un jour férié : +40 %.', max_digits=5, verbose_name='Majoration dimanche / jour férié (%)'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='ot_rate_tier1',
            field=models.DecimalField(decimal_places=2, default=20, help_text='1re à 8e heure sup hebdomadaire (41e–48e h) : +20 %.', max_digits=5, verbose_name='Majoration heures sup 1-8 (%)'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='ot_rate_tier2',
            field=models.DecimalField(decimal_places=2, default=30, help_text='9e à 16e heure sup (49e–56e h) : +30 %.', max_digits=5, verbose_name='Majoration heures sup 9-16 (%)'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='ot_rate_tier3',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Au-delà de la 16e heure sup (57e h et +) : +40 %.', max_digits=5, verbose_name='Majoration heures sup au-delà (%)'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='overtime_min_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text="Minutes à rester après la fin du travail pour annuler un retard (30 min → jusqu'à 17h30).", verbose_name='Heures sup minimum pour rattraper un retard'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='work_end_min',
            field=models.PositiveSmallIntegerField(default=1020, help_text='Fin de la journée de travail (17h00). Les heures supplémentaires démarrent après.', verbose_name='Heure de fin de travail'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='work_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Durée journalière. Base de la retenue pour absence (1 jour = N heures).', max_digits=4, verbose_name='Heures de travail par jour'),
        ),
    ]
