# Generated by Django 6.0.5 on 2026-06-03 12:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('channel', models.CharField(choices=[('DIGITAL', 'Digitale'), ('TERRAIN', 'Terrain'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('MIX', 'Multicanal')], default='DIGITAL', max_length=10, verbose_name='Canal')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('ACTIVE', 'En cours'), ('DONE', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=10, verbose_name='Statut')),
                ('objectives', models.TextField(blank=True, verbose_name='Objectifs')),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Budget (FCFA)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('target_reach', models.PositiveIntegerField(blank=True, null=True, verbose_name='Portée visée')),
                ('actual_reach', models.PositiveIntegerField(blank=True, null=True, verbose_name='Portée atteinte')),
                ('leads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Leads générés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='business.client', verbose_name='Marque / Client')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='projects.project', verbose_name='Projet lié')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('LOGO', 'Logo'), ('CHARTE', 'Charte graphique'), ('DOC', 'Document')], default='IMAGE', max_length=10, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='marketing/library/%Y/%m/', verbose_name='Fichier')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Mots-clés')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='business.client', verbose_name='Marque / Client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médiathèque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('TIKTOK', 'TikTok'), ('WHATSAPP', 'WhatsApp'), ('X', 'X (Twitter)'), ('OTHER', 'Autre')], default='FACEBOOK', max_length=10, verbose_name='Plateforme')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('media', models.FileField(blank=True, null=True, upload_to='marketing/posts/%Y/%m/', verbose_name='Visuel / Vidéo')),
                ('scheduled_at', models.DateTimeField(verbose_name='Programmé le')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'À valider'), ('APPROVED', 'Validé'), ('PUBLISHED', 'Publié'), ('REJECTED', 'Rejeté')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('review_comment', models.CharField(blank=True, max_length=255, verbose_name='Commentaire de validation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_crees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='business.client', verbose_name='Marque / Client')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='marketing.campaign', verbose_name='Campagne')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Calendrier éditorial',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
