# Generated by Django 6.0.5 on 2026-06-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du test')),
                ('hypothesis', models.TextField(verbose_name='Hypothèse')),
                ('variant_a', models.TextField(verbose_name='Variante A')),
                ('variant_b', models.TextField(verbose_name='Variante B')),
                ('metric', models.CharField(max_length=100, verbose_name='Métrique mesurée')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('RUNNING', 'En cours'), ('DONE', 'Terminé')], default='PLANNED', max_length=8, verbose_name='Statut')),
                ('winner', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, verbose_name='Gagnant')),
                ('result', models.TextField(blank=True, verbose_name='Résultat / Décision actée')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Test A/B',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('platform', models.CharField(choices=[('GOOGLE', 'Google Ads'), ('META', 'Meta Ads'), ('TIKTOK', 'TikTok Ads'), ('LINKEDIN', 'LinkedIn Ads'), ('OTHER', 'Autre')], max_length=10, verbose_name='Plateforme')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('ENDED', 'Terminée'), ('DRAFT', 'Brouillon')], default='DRAFT', max_length=6, verbose_name='Statut')),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Budget total (FCFA)')),
                ('spent', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Dépensé (FCFA)')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='Conversions')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('notes', models.TextField(blank=True, verbose_name='Résultats / Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='marketing.campaign')),
            ],
            options={
                'verbose_name': 'Campagne Ads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('preview_text', models.CharField(blank=True, max_length=200, verbose_name="Texte d'aperçu")),
                ('content', models.TextField(blank=True, verbose_name='Contenu HTML')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Planifiée'), ('SENT', 'Envoyée'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoi planifié')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('opens', models.PositiveIntegerField(default=0, verbose_name='Ouvertures')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('unsubscribes', models.PositiveIntegerField(default=0, verbose_name='Désabonnements')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to='marketing.campaign')),
            ],
            options={
                'verbose_name': 'Email marketing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('source', models.CharField(choices=[('SEO', 'SEO'), ('SEA', 'SEA / Ads'), ('SOCIAL', 'Réseaux sociaux'), ('REFERRAL', 'Référence'), ('EVENT', 'Événement'), ('OTHER', 'Autre')], default='OTHER', max_length=10, verbose_name='Source')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('CONTACTED', 'Contacté'), ('QUALIFIED', 'Qualifié'), ('CONVERTED', 'Converti'), ('LOST', 'Perdu')], default='NEW', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_contact', models.DateField(blank=True, null=True, verbose_name='Dernier contact')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assignes', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_entries', to='marketing.campaign')),
            ],
            options={
                'verbose_name': 'Lead / Prospect',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Mot-clé')),
                ('url', models.URLField(blank=True, verbose_name='URL cible')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('previous_position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position précédente')),
                ('search_volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume de recherche/mois')),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Difficulté (0-100)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Opportunités')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Mis à jour le')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_keywords', to='marketing.campaign')),
            ],
            options={
                'verbose_name': 'Mot-clé SEO',
                'ordering': ['position'],
            },
        ),
    ]
