# Generated by Django 6.0.5 on 2026-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur principal'), ('CEO', 'Directeur Général (CEO)'), ('RH', 'Responsable RH'), ('MANAGER', 'Responsable de service'), ('EMPLOYE', 'Employé'), ('CLIENT', 'Client'), ('PARTENAIRE', 'Partenaire'), ('FOURNISSEUR', 'Fournisseur'), ('CONSULTANT', 'Consultant externe')], default='EMPLOYE', max_length=20, verbose_name='Rôle'),
        ),
    ]
