# Generated by Django 6.0.5 on 2026-06-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_roles',
            field=models.CharField(blank=True, help_text="Codes de rôles séparés par des virgules (ex. RH,MANAGER). Permet à l'utilisateur de basculer entre plusieurs fonctions.", max_length=120, verbose_name='Rôles supplémentaires'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur principal'), ('CEO', 'Directeur Général (CEO)'), ('RH', 'Responsable RH'), ('MANAGER', 'Responsable de service'), ('EMPLOYE', 'Employé'), ('CLIENT', 'Client'), ('PARTENAIRE', 'Partenaire'), ('FOURNISSEUR', 'Fournisseur'), ('CONSULTANT', 'Consultant externe')], default='EMPLOYE', max_length=20, verbose_name='Rôle principal'),
        ),
    ]
