# Generated by Django 6.0.5 on 2026-06-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='user',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='cachets/', verbose_name='Cachet'),
        ),
    ]
