# Generated by Django 6.0.5 on 2026-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_signature_user_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Dernière activité'),
        ),
    ]
