# Generated by Django 6.0.5 on 2026-06-19 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_accounts',
            field=models.ManyToManyField(blank=True, help_text="Autres comptes appartenant à la MÊME personne. Permet de basculer de l'un à l'autre sans se reconnecter (réservé au super administrateur). Chaque action reste tracée.", to=settings.AUTH_USER_MODEL, verbose_name='Comptes liés'),
        ),
    ]
