# Generated by Django 6.0.5 on 2026-06-04 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='team_owner',
            field=models.ForeignKey(blank=True, help_text='Pour une visibilité « Mon équipe » : le responsable propriétaire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_equipe', to=settings.AUTH_USER_MODEL, verbose_name="Responsable de l'équipe"),
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'Tout le personnel'), ('TEAM', 'Mon équipe (responsable)'), ('MANAGERS', 'Responsables et RH'), ('RH', 'RH et direction'), ('ADMIN', 'Administration uniquement')], default='ALL', max_length=10, verbose_name='Visibilité'),
        ),
    ]
