# Generated by Django 6.0.5 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_team_owner_alter_document_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text="Lecture en ligne seule (pas de téléchargement ni d'impression), avec filigrane.", verbose_name='Confidentiel'),
        ),
    ]
