# Generated by Django 6.0.5 on 2026-06-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_is_confidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'Tout le personnel'), ('COLLEAGUES', 'Mes collègues (mon département)'), ('MY_MANAGER', 'Mon responsable'), ('COLL_MGR', 'Mes collègues et mon responsable'), ('TEAM', 'Mon équipe (responsable)'), ('MANAGERS', 'Responsables et RH'), ('RH', 'RH et direction'), ('ADMIN', 'Administration uniquement')], default='ALL', max_length=10, verbose_name='Visibilité'),
        ),
    ]
