# Generated by Django 6.0.5 on 2026-06-02 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('kind', models.CharField(choices=[('MEETING', 'Réunion'), ('EVENT', 'Événement'), ('BIRTHDAY', 'Anniversaire'), ('REMINDER', 'Rappel')], default='EVENT', max_length=10, verbose_name='Type')),
                ('start', models.DateTimeField(verbose_name='Début')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Calendrier & événements',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'Information générale'), ('RH', 'Note RH'), ('EVENT', 'Événement'), ('ALERT', 'Annonce importante')], default='GENERAL', max_length=10, verbose_name='Catégorie')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Résumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/%Y/%m/', verbose_name='Image')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Épinglé (bannière)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publié le')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communication.news')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['created_at'],
            },
        ),
    ]
