# Generated by Django 6.0.5 on 2026-06-11 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'événement")),
                ('brief', models.TextField(blank=True, verbose_name='Brief')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Budget (FCFA)')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('ACTIVE', 'En préparation'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=10, verbose_name='Statut')),
                ('retro_planning', models.TextField(blank=True, verbose_name='Rétroplanning')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='communication.event')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet événement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('status', models.CharField(choices=[('INVITED', 'Invité'), ('REGISTERED', 'Inscrit'), ('ATTENDED', 'Présent'), ('ABSENT', 'Absent')], default='INVITED', max_length=10, verbose_name='Statut')),
                ('badge_printed', models.BooleanField(default=False, verbose_name='Badge imprimé')),
                ('notes', models.TextField(blank=True)),
                ('event_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communication.eventproject')),
            ],
            options={
                'verbose_name': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Résumé')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('budget_spent', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Budget dépensé (FCFA)')),
                ('feedback', models.TextField(blank=True, verbose_name='Retours clients / participants')),
                ('kpis', models.TextField(blank=True, verbose_name='KPIs atteints')),
                ('learnings', models.TextField(blank=True, verbose_name='Enseignements pour la suite')),
                ('photos_url', models.URLField(blank=True, verbose_name='Lien album photos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_reports', to=settings.AUTH_USER_MODEL)),
                ('event_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='communication.eventproject')),
            ],
            options={
                'verbose_name': 'Bilan post-événement',
            },
        ),
        migrations.CreateModel(
            name='EventSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du prestataire')),
                ('service', models.CharField(max_length=200, verbose_name='Prestation')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('quote_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant devis (FCFA)')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CONTACTED', 'Contacté'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='PROSPECT', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True)),
                ('event_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='communication.eventproject')),
            ],
            options={
                'verbose_name': 'Prestataire événement',
            },
        ),
        migrations.CreateModel(
            name='KeyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PITCH', 'Pitch / Présentation'), ('FAQ', 'FAQ interne'), ('RESPONSE', 'Réponse type'), ('SPEECH', 'Discours officiel'), ('OTHER', 'Autre')], max_length=10, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('audience', models.CharField(blank=True, max_length=200, verbose_name='Audience cible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message clé',
                'verbose_name_plural': 'Messages clés',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=8, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('opens', models.PositiveIntegerField(default=0, verbose_name='Ouvertures')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PressReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name="Titre de l'article")),
                ('source', models.CharField(max_length=200, verbose_name='Source / Média')),
                ('media_type', models.CharField(choices=[('ONLINE', 'En ligne'), ('PRINT', 'Presse écrite'), ('TV', 'Télévision'), ('RADIO', 'Radio'), ('SOCIAL', 'Réseaux sociaux')], default='ONLINE', max_length=8, verbose_name='Type de média')),
                ('tone', models.CharField(choices=[('POSITIVE', 'Positif'), ('NEUTRAL', 'Neutre'), ('NEGATIVE', 'Négatif')], default='NEUTRAL', max_length=8, verbose_name='Tonalité')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extrait / Citation')),
                ('published_at', models.DateField(verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de presse',
                'verbose_name_plural': 'Revue de presse',
                'ordering': ['-published_at'],
            },
        ),
    ]
