# Generated by Django 6.0.5 on 2026-06-15 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_eventproject_eventparticipant_eventreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='mod_status',
            field=models.CharField(choices=[('PENDING', 'En attente de validation'), ('APPROVED', 'Validée'), ('REJECTED', 'Refusée')], default='APPROVED', max_length=10, verbose_name='Validation'),
        ),
        migrations.AddField(
            model_name='news',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Motif de refus'),
        ),
        migrations.AddField(
            model_name='news',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validée le'),
        ),
        migrations.AddField(
            model_name='news',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
    ]
