# Generated by Django 6.0.5 on 2026-06-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_groupmessage_deleted_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False, verbose_name='Transféré'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False, verbose_name='Transféré'),
        ),
    ]
