# Generated by Django 6.0.5 on 2026-06-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_groupmessage_is_forwarded_message_is_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Message système'),
        ),
    ]
