# Generated by Django 6.0.5 on 2026-06-07 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_groupmessage_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='chat_groups_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs du groupe'),
        ),
    ]
