# Generated by Django 6.0.5 on 2026-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_conversationclear'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modifié le'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Modifié le'),
        ),
    ]
