# Generated by Django 6.0.5 on 2026-06-19 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='taches_partagees', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à (équipe)'),
        ),
    ]
