# Generated by Django 6.0.5 on 2026-06-03 11:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom / Société')),
                ('kind', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CLIENT', 'Client')], default='PROSPECT', max_length=10, verbose_name='Type')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Personne de contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('sector', models.CharField(blank=True, max_length=120, verbose_name="Secteur d'activité")),
                ('city', models.CharField(blank=True, default='Douala', max_length=80, verbose_name='Ville')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extranet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_client', to=settings.AUTH_USER_MODEL, verbose_name='Compte extranet lié')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_geres', to=settings.AUTH_USER_MODEL, verbose_name='Commercial en charge')),
            ],
            options={
                'verbose_name': 'Client / Prospect',
                'verbose_name_plural': 'Clients & prospects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='N° facture')),
                ('kind', models.CharField(choices=[('CLIENT', 'Facture client'), ('SUPPLIER', 'Facture fournisseur')], default='CLIENT', max_length=10, verbose_name='Type')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('title', models.CharField(max_length=200, verbose_name='Objet')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Émise'), ('PARTIAL', 'Partiellement payée'), ('PAID', 'Payée'), ('OVERDUE', 'Échue impayée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5, verbose_name='TVA (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='business.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Prix unitaire (FCFA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business.invoice')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant estimé (FCFA)')),
                ('stage', models.CharField(choices=[('NEW', 'Nouveau'), ('QUALIFIED', 'Qualifié'), ('PROPOSAL', 'Proposition'), ('NEGOTIATION', 'Négociation'), ('WON', 'Gagné'), ('LOST', 'Perdu')], default='NEW', max_length=12, verbose_name='Étape')),
                ('probability', models.PositiveSmallIntegerField(default=20, verbose_name='Probabilité (%)')),
                ('expected_close', models.DateField(blank=True, null=True, verbose_name='Clôture prévue')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='business.client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Opportunité',
                'verbose_name_plural': 'Opportunités (pipeline)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK', 'Virement bancaire'), ('MOMO', 'MTN Mobile Money'), ('OM', 'Orange Money'), ('CHEQUE', 'Chèque')], default='MOMO', max_length=10, verbose_name='Moyen de paiement')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='Référence transaction')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business.invoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='N° devis')),
                ('title', models.CharField(max_length=200, verbose_name='Objet')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('INTERNAL', 'Validation interne'), ('SENT', 'Envoyé au client'), ('SIGNED', 'Signé / Accepté'), ('REFUSED', 'Refusé')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name="Date d'émission")),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.25'), max_digits=5, verbose_name='TVA (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Conditions / Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='business.client')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to=settings.AUTH_USER_MODEL, verbose_name='Établi par')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='business.quote'),
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Prix unitaire (FCFA)')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business.quote')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
            },
        ),
    ]
