# Generated by Django 6.0.5 on 2026-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signé le'),
        ),
        migrations.AddField(
            model_name='quote',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Signé par'),
        ),
        migrations.AddField(
            model_name='quote',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de signature'),
        ),
    ]
