# Generated by Django 6.0.5 on 2026-06-03 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_quote_signed_at_quote_signed_by_name_quote_signed_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('INTERNAL', 'Validation interne'), ('SENT', 'Envoyé au client'), ('CHANGES', 'Modifications demandées'), ('SIGNED', 'Signé / Accepté'), ('REFUSED', 'Refusé')], default='DRAFT', max_length=10, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='QuoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SENT', 'Envoyé au client'), ('SIGNED', 'Accepté et signé'), ('REFUSED', 'Refusé par le client'), ('CHANGES', 'Modifications demandées'), ('UPDATED', 'Mise à jour interne')], max_length=10, verbose_name='Action')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_events', to=settings.AUTH_USER_MODEL, verbose_name='Par')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='business.quote')),
            ],
            options={
                'verbose_name': 'Événement de devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
