# Generated by Django 6.0.5 on 2026-06-04 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_quote_status_quoteevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_validated',
            field=models.BooleanField(default=True, verbose_name='Validé par la Direction'),
        ),
        migrations.AddField(
            model_name='client',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
