# Generated by Django 6.0.5 on 2026-06-02 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('WARNING', 'Avertissement écrit'), ('REPRIMAND', 'Blâme'), ('SUSPENSION', 'Mise à pied (1 à 8 jours)'), ('DISMISSAL', 'Licenciement')], max_length=12, verbose_name='Type de sanction')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CONVENED', 'Salarié convoqué (entretien préalable)'), ('NOTIFIED', 'Sanction notifiée'), ('CLOSED', 'Clôturée / contestée')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('facts', models.TextField(verbose_name='Faits reprochés')),
                ('fault_date', models.DateField(blank=True, null=True, verbose_name='Date des faits')),
                ('hearing_date', models.DateField(blank=True, null=True, verbose_name="Date de l'entretien préalable")),
                ('employee_defense', models.TextField(blank=True, verbose_name='Explications du salarié')),
                ('suspension_days', models.PositiveSmallIntegerField(blank=True, help_text='1 à 8 jours maximum (Code du Travail).', null=True, verbose_name='Durée de mise à pied (jours)')),
                ('suspension_start', models.DateField(blank=True, null=True, verbose_name='Début de la mise à pied')),
                ('notified_at', models.DateField(blank=True, null=True, verbose_name='Notifiée le')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL, verbose_name='Prononcée par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_records', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Dossier disciplinaire',
                'verbose_name_plural': 'Dossiers disciplinaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
