# Generated by Django 6.0.5 on 2026-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='reference',
            field=models.CharField(blank=True, max_length=30, verbose_name='Référence document'),
        ),
    ]
