# Generated by Django 6.0.5 on 2026-06-02 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('name', models.CharField(max_length=120, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Libellé')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Payé')),
                ('deducts_balance', models.BooleanField(default=True, help_text='Décoché pour la maladie, la maternité ou les permissions exceptionnelles.', verbose_name='Décompté du solde annuel')),
                ('default_days', models.PositiveSmallIntegerField(default=0, help_text='Durée de référence, ex. 98 jours pour la maternité (14 semaines).', verbose_name='Durée légale (jours)')),
                ('color', models.CharField(default='#0073DE', max_length=7, verbose_name='Couleur (hex)')),
                ('legal_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence légale')),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Jours (+/-)')),
                ('reason', models.CharField(max_length=200, verbose_name='Motif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Ajustement de solde',
                'verbose_name_plural': 'Ajustements de solde',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.TextField(blank=True, verbose_name='Motif')),
                ('days_count', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Jours ouvrables')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumise'), ('MANAGER_APPROVED', 'Validée par le responsable'), ('APPROVED', 'Validée (RH)'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée')], default='SUBMITTED', max_length=20, verbose_name='Statut')),
                ('manager_comment', models.CharField(blank=True, max_length=255, verbose_name='Commentaire responsable')),
                ('rh_comment', models.CharField(blank=True, max_length=255, verbose_name='Commentaire RH')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Soumise le')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décidée le')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Employé')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_manager_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_rh_decisions', to=settings.AUTH_USER_MODEL, verbose_name='RH')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='conges.leavetype', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-created_at'],
            },
        ),
    ]
