# Generated by Django 6.0.5 on 2026-06-03 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_leaverequest_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager_comment',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='rh',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='rh_comment',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='current_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Niveau courant'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En cours de validation'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Niveau')),
                ('role', models.CharField(max_length=20, verbose_name='Rôle validateur')),
                ('approved', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='conges.leaverequest')),
            ],
            options={
                'verbose_name': 'Validation de congé',
                'verbose_name_plural': 'Validations de congé',
                'ordering': ['level'],
            },
        ),
    ]
