# Generated by Django 6.0.5 on 2026-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('INTERNAL', 'Intranet'), ('EXTERNAL', 'Extranet')], default='INTERNAL', help_text='Cloisonne les notifications intranet et extranet.', max_length=8, verbose_name='Périmètre'),
        ),
    ]
